package repository

import (
	"context"
	"errors"

	"gorm.io/gorm"

	"github.com/admin-template/backend/internal/model"
)

// OrderRepository. OrderNo is generated by the service layer (so the format
// is consistent across rows) — this repo only persists it.
type OrderRepository interface {
	Create(ctx context.Context, o *model.Order) error
	Update(ctx context.Context, o *model.Order) error
	GetByID(ctx context.Context, id uint64) (*model.Order, error)
	GetByOrderNo(ctx context.Context, orderNo string) (*model.Order, error)
	GetByApplication(ctx context.Context, applicationID uint64) (*model.Order, error)
	ListByStudent(ctx context.Context, page, size int, studentID uint64, status int8) ([]model.Order, int64, error)
	ListByEmployer(ctx context.Context, page, size int, employerID uint64, status int8) ([]model.Order, int64, error)
	ListAll(ctx context.Context, page, size int, status int8) ([]model.Order, int64, error)
	UpdateFields(ctx context.Context, id uint64, fields map[string]any) error
}

type orderRepo struct{ db *gorm.DB }

func NewOrderRepository(db *gorm.DB) OrderRepository { return &orderRepo{db: db} }

func (r *orderRepo) Create(ctx context.Context, o *model.Order) error {
	return r.db.WithContext(ctx).Create(o).Error
}

func (r *orderRepo) Update(ctx context.Context, o *model.Order) error {
	return r.db.WithContext(ctx).Save(o).Error
}

func (r *orderRepo) GetByID(ctx context.Context, id uint64) (*model.Order, error) {
	var o model.Order
	err := r.db.WithContext(ctx).First(&o, id).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &o, nil
}

func (r *orderRepo) GetByOrderNo(ctx context.Context, orderNo string) (*model.Order, error) {
	var o model.Order
	err := r.db.WithContext(ctx).Where("order_no = ?", orderNo).First(&o).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &o, nil
}

func (r *orderRepo) GetByApplication(ctx context.Context, applicationID uint64) (*model.Order, error) {
	var o model.Order
	err := r.db.WithContext(ctx).Where("application_id = ?", applicationID).First(&o).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &o, nil
}

func (r *orderRepo) ListByStudent(ctx context.Context, page, size int, studentID uint64, status int8) ([]model.Order, int64, error) {
	return r.list(ctx, page, size, "student_id = ?", []any{studentID}, status)
}

func (r *orderRepo) ListByEmployer(ctx context.Context, page, size int, employerID uint64, status int8) ([]model.Order, int64, error) {
	return r.list(ctx, page, size, "employer_id = ?", []any{employerID}, status)
}

func (r *orderRepo) ListAll(ctx context.Context, page, size int, status int8) ([]model.Order, int64, error) {
	return r.list(ctx, page, size, "1 = 1", nil, status)
}

func (r *orderRepo) list(ctx context.Context, page, size int, where string, args []any, status int8) ([]model.Order, int64, error) {
	var out []model.Order
	var total int64
	q := r.db.WithContext(ctx).Model(&model.Order{}).Where(where, args...)
	if status > 0 {
		q = q.Where("status = ?", status)
	}
	if err := q.Count(&total).Error; err != nil {
		return nil, 0, err
	}
	off := (page - 1) * size
	err := q.Order("id DESC").Offset(off).Limit(size).Find(&out).Error
	return out, total, err
}

func (r *orderRepo) UpdateFields(ctx context.Context, id uint64, fields map[string]any) error {
	return r.db.WithContext(ctx).Model(&model.Order{}).Where("id = ?", id).Updates(fields).Error
}
