package model

import (
	"time"
)

// Message is an in-app notification row surfaced on the bell icon. It is
// generated by the system (admin broadcast, order state transitions) and
// pushed to a single recipient. Link is a deep-link path the mini-program
// uses for navigation (e.g. "pages/job-detail/index?id=42").
type Message struct {
	Base
	UserID  uint64     `gorm:"index;not null"  json:"user_id"`
	Type    int8       `gorm:"default:1;index" json:"type"` // 1=系统通知 2=岗位相关 3=订单相关 4=评价相关
	Title   string     `gorm:"size:128"        json:"title"`
	Content string     `gorm:"type:text"       json:"content"`
	Link    string     `gorm:"size:255"        json:"link"`
	IsRead  bool       `gorm:"default:false"   json:"is_read"`
	ReadAt  *time.Time `                       json:"read_at"`
}

func (Message) TableName() string { return "messages" }
